### ISSUE TITLE
Create .travis.yml to use the test cases and do Continuous Integration

### ISSUE THREAD

**Issue by achoudh5** [achoudh5/Manipulating_Excel_Sheet#8]
- Use the unit tests and check for any errors

- Errors should be sent to a slack channel, use something like below:-

```
notifications: 
  slack: 
   rooms:
     - secure: <channel_key>
   on_success: always
   on_failure: always
   template:
     - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
     - "Execution time: *%{duration}*"
     - "Message: %{message}"
```
